name: CI/CD Build, Test, and Deploy Flask Docker App

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Run lint checks
      run: flake8 .

    - name: Run unit tests
      run: pytest

    - name: Build Docker image (test)
      run: docker build -t flask-ec2-app .

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/flask-ec2-app
          git pull origin main
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true
          sudo docker build -t flask-ec2-app .
          sudo docker run -d --name flask-app -p 8000:8000 flask-ec2-app
        EOF


